version: '3'
services:
   nginx:
       image: nginx:latest
       container_name: nginx
       volumes:
           - ./default.conf:/etc/nginx/conf.d/default.conf:ro
       ports:
          - 80:80 #เปลี่ยนเป็น port อื่นหาก port ซ่ำ ก็จะได้ - 8084:80
          - 443:443